# Generated by Django 6.1 on 2026-09-26 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservation", "0004_reservation_total_amount_recived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room", "Room"),
                            ("add_on", "Add On"),
                            ("food", "Food"),
                        ],
                        default="room",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "state_tax_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "central_tax_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.reservation",
                    ),
                ),
            ],
        ),
    ]
