# Generated by Django 6.1 on 2026-09-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_created_at_transaction_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
