# Generated by Django 6.1 on 2026-09-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_reservation_total_amount_recived"),
        ("transactions", "0003_transaction_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="reservation.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("ROOM", "Room"), ("ADD_ON", "Add On"), ("FOOD", "Food")],
                default="ROOM",
                max_length=10,
            ),
        ),
    ]
