# Generated by Django 6.1 on 2026-09-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("adhar_card", "Adhar Card"),
                            ("driving_card", "Driving Card"),
                            ("voter_card", "Voter Card"),
                            ("other", "Other"),
                        ],
                        default="adhar_card",
                        max_length=20,
                    ),
                ),
                ("id_value", models.CharField(max_length=50)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="hotel.hotel",
                    ),
                ),
            ],
        ),
    ]
