# Generated by Django 6.1 on 2026-09-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(default="nomail@localhost.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="guest",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=10),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("check_in", "Check In"),
                            ("canceled", "Canceled"),
                            ("check_out", "Check Out"),
                        ],
                        default="check_in",
                        max_length=30,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotel.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotel.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_guests",
                        to="hotel.guest",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_guests",
                        to="hotel.reservation",
                    ),
                ),
            ],
        ),
    ]
