# Generated by Django 6.1 on 2026-09-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_guest_email_alter_guest_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="gender",
            field=models.TextField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                null=True,
            ),
        ),
    ]
