# Generated by Django 6.1 on 2026-09-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_guest_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationguest",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="room",
        ),
        migrations.RemoveField(
            model_name="reservationguest",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.DeleteModel(
            name="ReservationGuest",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
