# Generated by Django 6.1 on 2026-09-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0005_remove_reservationguest_guest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        null=True,
                    ),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(default="1234567890", max_length=10)),
                (
                    "email",
                    models.EmailField(default="nomail@localhost.com", max_length=254),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("adhar_card", "Adhar Card"),
                            ("driving_card", "Driving Card"),
                            ("voter_card", "Voter Card"),
                            ("other", "Other"),
                        ],
                        default="adhar_card",
                        max_length=20,
                    ),
                ),
                ("id_value", models.CharField(max_length=50)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="hotel.hotel",
                    ),
                ),
            ],
        ),
    ]
