# Generated by Django 6.1 on 2026-09-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0001_initial"),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationguest",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="guest.guest",
            ),
        ),
        migrations.AlterField(
            model_name="reservationguest",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="reservation.reservation",
            ),
        ),
    ]
