# Generated by Django 6.1 on 2026-09-25 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0001_initial"),
        ("reservation", "0002_alter_reservationguest_guest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationguest",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_guests",
                to="guest.guest",
            ),
        ),
        migrations.AlterField(
            model_name="reservationguest",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_guests",
                to="reservation.reservation",
            ),
        ),
    ]
