# Generated by Django 6.1 on 2026-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_reservationguest_guest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="total_amount_recived",
            field=models.IntegerField(default=0),
        ),
    ]
