# Generated by Django 6.1 on 2026-09-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_reservation_total_amount_recived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="total_amount_recived",
            field=models.FloatField(default=0),
        ),
    ]
