# Generated by Django 6.1 on 2026-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_reservation_total_amount_recived"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="remarks",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
