# Generated by Django 6.1 on 2026-09-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0001_initial"),
        ("reservation", "0006_reservation_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="guests",
            field=models.ManyToManyField(
                through="reservation.ReservationGuest", to="guest.guest"
            ),
        ),
        migrations.AlterField(
            model_name="reservationguest",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.reservation",
            ),
        ),
    ]
