# Generated by Django 6.1 on 2026-09-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0001_initial"),
        ("reservation", "0007_reservation_guests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationguest",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="guest.guest"
            ),
        ),
    ]
